# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181120_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=35),
        ),
    ]
